"""Read-only portfolio companion; business calculations come from TypeScript snapshots."""
import json
from decimal import Decimal
from pathlib import Path
import streamlit as st

st.set_page_config(page_title="Business Analyst Agent", page_icon="📊", layout="wide")
st.markdown("<style>[data-testid=stMetricValue] {font-size: 1.35rem;} [data-testid=stMetricLabel] {min-height: 2.8em;}</style>", unsafe_allow_html=True)
ROOT = Path(__file__).resolve().parent
snapshot = json.loads((ROOT / "showcase/snapshot.json").read_text())
if snapshot.get("demo") is not True:
    st.error("Only validated synthetic demo snapshots may be displayed.")
    st.stop()


def display(value, unit):
    if value is None:
        return "Unavailable"
    number = Decimal(value)
    if unit == "currency":
        return f"${number:,.2f}"
    if unit == "percent":
        return f"{number:,.2f}%"
    if unit == "duration":
        return f"{number:,.2f} min"
    return f"{number:,.0f}"


with st.sidebar:
    st.title("Business Analyst")
    st.caption("EVIDENCE-BACKED BUSINESS INSIGHTS")
    organization = st.selectbox("Demo organization", [o["name"] for o in snapshot["organizations"]])
    page = st.radio("Workspace", ["Overview", "Sales", "Billing", "Operations", "Investigations", "About the project"])
    st.divider()
    st.info("Synthetic data only. No real customers, live connections, or API keys.")
    st.link_button("View full project on GitHub", "https://github.com/mdsaeed24/business-analyst-agent")

org = next(o for o in snapshot["organizations"] if o["name"] == organization)
metrics = {m["key"]: m for m in org["metrics"]}
st.caption(f"{organization.upper()} / PORTFOLIO SHOWCASE")
st.title("Business overview" if page == "Overview" else page)
st.write("Understand the numbers. Explore the evidence. Know what to ask next.")
st.info("DEMO DATA · A read-only Streamlit companion to the full Next.js application. All figures come from validated synthetic-data calculations.")
st.caption(f"August 2026 vs July 2026 · Reporting timezone: {org['timezone']} · Engine {snapshot['engineVersion']} · Fixed saved periods, not a live feed")

sections = {
    "Overview": ["revenue_collected", "mrr", "new_customers", "win_rate"],
    "Sales": ["pipeline_created", "win_rate", "new_customers", "web_conversion_rate"],
    "Billing": ["revenue_collected", "mrr", "new_customers"],
    "Operations": ["support_volume", "avg_first_response", "web_conversion_rate"],
}
if page in sections:
    keys = sections[page]
    for column, key in zip(st.columns(len(keys)), keys):
        m = metrics[key]
        finding = m["finding"]
        delta = finding.get("delta") if m["unit"] == "percent" else finding.get("relativePercent")
        suffix = " pp" if m["unit"] == "percent" else "%"
        with column:
            st.metric(m["name"], display(m["current"]["value"], m["unit"]), None if delta is None else f"{Decimal(delta):+.2f}{suffix}", delta_color="off", border=True)
    st.subheader("Period comparisons")
    for column, key in zip(st.columns(min(3, len(keys))), keys[:3]):
        m = metrics[key]
        with column:
            st.markdown(f"**{m['name']}**")
            st.bar_chart({"Period": [snapshot["baseline"], snapshot["current"]], "Value": [None if m[p]["value"] is None else float(m[p]["value"]) for p in ["baseline", "current"]]}, x="Period", y="Value", color="#8460d1", height=260, sort=False)
            st.text(f"July: {display(m['baseline']['value'], m['unit'])} · August: {display(m['current']['value'], m['unit'])}")
    st.subheader("Explore the evidence")
    for key in keys:
        m = metrics[key]
        with st.expander(f"{m['name']} · calculation evidence"):
            st.code(m["formula"], language=None)
            st.write(f"August: {m['current']['sourceCount']} source records · July: {m['baseline']['sourceCount']} source records")
            st.json({p: {k: m[p][k] for k in ["value", "status", "numerator", "denominator", "inputHash"]} for p in ["current", "baseline"]})
            for limitation in m["current"]["limitations"]:
                st.caption(limitation)
    st.success("Next: open Investigations in the sidebar to explore the changes and suggested follow-up checks.")
elif page == "Investigations":
    st.subheader("What changed between July and August?")
    st.caption("Generated by the project's deterministic TypeScript investigation rules. These are observed changes, not causal explanations or statistical significance tests.")
    flagged_only = st.checkbox("Show only changes meeting the investigation threshold")
    shown = 0
    for m in metrics.values():
        f = m["finding"]
        if flagged_only and not f["significant"]:
            continue
        shown += 1
        with st.container(border=True):
            st.subheader(m["name"])
            st.caption(f["state"].replace("_", " "))
            st.write(f["statement"])
            st.write(f"**Suggested follow-up:** {f['nextStep']}")
    if not shown:
        st.info("No changes meet the selected rules.")
    st.caption("The full Next.js app also supports saved AI explanations and ElevenLabs voice briefings. This public companion does not generate AI content or call paid APIs.")
else:
    st.subheader("From source data to a business story")
    st.markdown("""
1. **Ingest:** validate CSV records, normalize identifiers, and upsert into PostgreSQL.
2. **Calculate:** deterministic TypeScript metrics with exact decimals and source snapshots.
3. **Investigate:** compare periods using explicit rules and traceable evidence.
4. **Explain:** optional grounded DeepSeek interpretation in the full application.
5. **Listen:** optional ElevenLabs AI briefings with cached audio in the full application.
""")
    st.markdown("**Full application:** Next.js, React, TypeScript, PostgreSQL, Prisma and Zod. Includes tenant isolation, authentication, role controls, and a read-only Stripe sync framework tested with mocked responses.")
    st.warning("This Streamlit companion showcases exported synthetic calculations. It does not run the Next.js server, authentication, database ingestion, live Stripe sync, or AI/voice generation. Those implementations are available in the GitHub project.")
    st.download_button("Download demo metric snapshot", (ROOT / "showcase/snapshot.json").read_bytes(), file_name="business-analyst-demo.json", mime="application/json")
    st.link_button("Explore architecture and setup", "https://github.com/mdsaeed24/business-analyst-agent#readme")
st.divider()
st.caption("Business Analyst Agent · Portfolio demonstration · Synthetic data · Deterministic metrics")
