import { z } from "zod";
import { boolean, currency, date, identifier as id, integer, lineage, money, nullable, rate, text, timestamp, timezone } from "./primitives";

export const organization = z.strictObject({ organization_id: id, organization_name: text, industry: text, timezone, currency, created_at: timestamp });
export const company = z.strictObject({ ...lineage, source_system: z.literal("hubspot"), company_id: id, company_name: text, industry: text, region: text, employee_count: integer, annual_revenue_usd: money, lifecycle_stage: z.enum(["churned", "customer", "lead", "prospect"]) });
export const contact = z.strictObject({ ...lineage, source_system: z.literal("hubspot"), contact_id: id, company_id: id, first_name: text, last_name: text, job_title: text, email: z.email(), region: text, lifecycle_stage: z.enum(["MQL", "SQL", "customer", "lead", "subscriber"]), created_date: date });
export const deal = z.strictObject({ ...lineage, source_system: z.literal("hubspot"), deal_id: id, company_id: id, deal_name: text, stage: z.enum(["closed_lost", "closed_won", "demo", "proposal", "qualification"]), amount_usd: money, created_date: date, close_date: nullable(date), owner_id: id, pipeline: text, is_closed_won: boolean }).refine((r) => r.is_closed_won === (r.stage === "closed_won"), { message: "is_closed_won must match stage", path: ["is_closed_won"] }).refine((r) => !r.close_date || r.close_date >= r.created_date, { message: "close_date precedes created_date", path: ["close_date"] }).refine((r) => !r.stage.startsWith("closed_") || r.close_date !== null, { message: "Closed deals require close_date", path: ["close_date"] });
export const customer = z.strictObject({ ...lineage, source_system: z.literal("stripe"), customer_id: id, company_id: id, customer_since: date, status: z.enum(["active", "canceled"]), country: z.string().regex(/^[A-Z]{2}$/) });
export const subscription = z.strictObject({ ...lineage, source_system: z.literal("stripe"), subscription_id: id, customer_id: id, plan: text, monthly_recurring_revenue_usd: money, status: z.enum(["active", "canceled"]), start_date: date, cancel_date: nullable(date) }).refine((r) => (r.status === "canceled") === (r.cancel_date !== null), { message: "cancel_date must match status", path: ["cancel_date"] }).refine((r) => !r.cancel_date || r.cancel_date >= r.start_date, { message: "cancel_date precedes start_date", path: ["cancel_date"] });
export const payment = z.strictObject({ ...lineage, source_system: z.literal("stripe"), payment_id: id, customer_id: id, subscription_id: id, payment_date: date, amount_usd: money, status: z.enum(["failed", "succeeded"]), payment_method: z.enum(["ach", "card"]), refund_amount_usd: money }).refine((r) => cents(r.refund_amount_usd) <= cents(r.amount_usd), { message: "Refund exceeds payment amount", path: ["refund_amount_usd"] });
function cents(value: string) { const [whole, fraction = ""] = value.split("."); return BigInt(whole) * 100n + BigInt(fraction.padEnd(2, "0")); }
export const ga4 = z.strictObject({ ...lineage, source_system: z.literal("ga4"), date, channel: text, sessions: integer, users: integer, conversions: integer, conversion_rate: rate, bounce_rate: rate, revenue_attributed_usd: money });
export const invoice = z.strictObject({ ...lineage, source_system: z.literal("quickbooks"), invoice_id: id, customer_id: id, invoice_date: date, due_date: date, amount_usd: money, status: z.enum(["paid", "open", "void", "uncollectible"]), paid_date: nullable(date) }).refine((r) => r.due_date >= r.invoice_date, { message: "due_date precedes invoice_date", path: ["due_date"] }).refine((r) => (r.status === "paid") === (r.paid_date !== null), { message: "paid_date must match status", path: ["paid_date"] }).refine((r) => !r.paid_date || r.paid_date >= r.invoice_date, { message: "paid_date precedes invoice_date", path: ["paid_date"] });
export const expense = z.strictObject({ ...lineage, source_system: z.literal("quickbooks"), expense_id: id, expense_date: date, category: text, vendor: text, amount_usd: money, department: text, is_recurring: boolean });
export const ticket = z.strictObject({ ...lineage, source_system: z.literal("zendesk"), ticket_id: id, customer_id: id, created_at: timestamp, priority: z.enum(["high", "low", "normal", "urgent"]), category: text, status: z.enum(["closed", "open", "pending", "solved"]), first_response_minutes: integer, resolution_minutes: nullable(integer), satisfaction_score: nullable(z.string().regex(/^[0-5](\.\d{1,2})?$/).refine((value) => Number(value) <= 5, "Score must be between 0 and 5")) });
export const sourceTables = ["crm_companies", "crm_contacts", "crm_deals", "stripe_customers", "stripe_subscriptions", "stripe_payments", "ga4_daily", "quickbooks_invoices", "quickbooks_expenses", "support_tickets"] as const;
export const metric = z.strictObject({ metric_key: id, metric_name: text, definition: text, unit: z.enum(["count", "currency", "duration", "percent"]), source_tables: text.transform((value) => value.split(",").map((part) => part.trim())).pipe(z.array(z.enum(sourceTables)).min(1)), timezone, currency: nullable(currency), version: z.string().regex(/^\d+\.\d+$/) }).refine((r) => r.unit !== "currency" || r.currency !== null, { message: "Currency metrics require currency", path: ["currency"] });
export const dictionary = z.strictObject({ file: text, primary_key: text, important_foreign_keys: z.string(), purpose: text });
